-- ============================================================
-- PROJECT 1 : BANKING & AML TRANSACTION MONITORING
-- Scenario 01: High-Value Successful Transactions
-- ============================================================

-- Business rule:
-- AMOUNT >= 1,000,000
-- AND BANK_TRANSACTION_STATUS = 'SUCCESS'

SELECT
    BANK_TRANSACTION_ID,
    ACCOUNT_ID,
    BANK_TRANSACTION_DATE,
    BANK_TRANSACTION_TYPE,
    AMOUNT,
    CURRENCY,
    COUNTRY,
    CHANNEL,
    REFERENCE_NUMBER,
    BANK_TRANSACTION_STATUS
FROM BANK_TRANSACTION
WHERE AMOUNT >= 1000000
  AND BANK_TRANSACTION_STATUS = 'SUCCESS'
ORDER BY AMOUNT DESC;


-- Validation count

SELECT COUNT(*) AS HIGH_VALUE_SUCCESSFUL_TXNS
FROM BANK_TRANSACTION
WHERE AMOUNT >= 1000000
  AND BANK_TRANSACTION_STATUS = 'SUCCESS';


-- Validation statistics

SELECT
    MIN(AMOUNT) AS MIN_AMOUNT,
    MAX(AMOUNT) AS MAX_AMOUNT,
    AVG(AMOUNT) AS AVG_AMOUNT
FROM BANK_TRANSACTION
WHERE AMOUNT >= 1000000
  AND BANK_TRANSACTION_STATUS = 'SUCCESS';